[workspace]
resolver = "2"
members = [
	"d9-balances",
	"d9-node-voting",
	"d9-referral",
	"d9-treasury",
	"d9-node-rewards",
	"d9-council-lock",
	"d9-multi-sig",
	"d9-candidate-registry",
	"d9-node-liveness",
	"d9-parameters",
	"d9-punishment",
	"d9-validator-oversight",
]
